# Generated by Django 2.1 on 2018-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
