# Generated by Django 2.1.4 on 2018-12-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(default='', max_length=250),
        ),
    ]
