# Generated by Django 2.1.4 on 2019-01-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
