# Generated by Django 2.1.5 on 2019-01-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alt',
        ),
    ]
