# Generated by Django 2.1.2 on 2018-11-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181031_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(default='', max_length=250),
        ),
    ]
