# Generated by Django 2.1.2 on 2018-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mpesaPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=40)),
                ('trans_id', models.CharField(max_length=40)),
                ('trans_time', models.DateField(auto_now_add=True)),
                ('trans_amount', models.CharField(max_length=40)),
                ('BusinessShortCode', models.CharField(max_length=15)),
                ('BillRefNumber', models.CharField(max_length=40)),
                ('InvoiceNumber', models.CharField(max_length=40)),
                ('ThirdPartyTransID', models.CharField(max_length=40)),
                ('MSISDN', models.CharField(max_length=40)),
                ('FirstName', models.CharField(max_length=40)),
                ('MiddleName', models.CharField(max_length=40)),
                ('OrgAccountBalance', models.CharField(max_length=40)),
            ],
        ),
    ]
